### ISSUE TITLE
tbl: rendering issues

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#13]
With the table available in the following manpage:
https://svnweb.freebsd.org/base/head/tools/tools/cxgbetool/cxgbetool.8?view=markup

the table is not aligned, the first row is correctly rendered but the next one start one char on the left from where the previous row started

**Comment by n-t-roff** [comment]
Interesting. I look into it. Thank you for reporting!

**Comment by n-t-roff** [comment]
It does work now. Note that `expand` is used for this table. expand makes the table as wide as the line length. Since the page offset is zero the table does not have an indent. (The indent in roff set with .in is part of the line length. So actually there seems to be a problem with the groff rendering now which shows an unexpected indent for the table.)

**Comment by bapt** [comment]
excellent :) thank you

**Comment by g-branden-robinson** [comment]
A comment for archeologists...

> With the table available in the following manpage:
> https://svnweb.freebsd.org/base/head/tools/tools/cxgbetool/cxgbetool.8?view=markup
> 
> the table is not aligned, the first row is correctly rendered but the next one start one char on the left from where the previous row started

That document has gone missing from FreeBSD but I have a copy dated "Sep 21, 2018".

I don't see the described problem when rendering the document with _groff_ 1.22.3 (November 2014).  (There is a _different_ problem when formatting using `nroff` and continuously rendering (the default); many blank lines appear at the top of the `matchtype` row.  This problem is fixed in _groff_ 1.23.0 (July 2023).  I think this was an instance of [Savannah #57665](https://savannah.gnu.org/bugs/index.php?57665)).
