### ISSUE TITLE
Fonts and case sensitivity

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#17]
I have notice that heirloom doctools is naming differently the Heletica Narrow bold fonts than GNU groff it is Hb in heirloom vs HNB in groff.

While I have no idea which is right and guess heirloom probably is right here, the groff naming have the nice side effect of allowing to checkout on case insensitive filesystem

Same happen with Hi, Hx and Hr

**Comment by n-t-roff** [comment]
If I understand it correctly this problem is in devpost only? You would need option -Tpost for troff to access these fonts since the standard option is -Tps. -Tpost has only the traditional low resolution of 720 units/inch whereas troff standard -Tps (devps) has 72000 units/inch.

What is planned:
* Files Hb, Hi, Hx, and Hr are renamed to the groff file name HNB, HNI, HNBI, and HNR
* All other file names are left unchanged
* The fonts for option -Tpost will be accessable under the current ditroff name and (now new) under the groff name

**Comment by bapt** [comment]
sounds like a good plan

**Comment by n-t-roff** [comment]
The four files are renamed and groff -Tps names can be used for troff -Tpost fonts. Note that font names with more than two characters only work for .ft and \f if xflag is set to at least 2.

**Comment by bapt** [comment]
Thank you!

**Comment by bapt** [comment]
There is on left issue on that subject:
troff/troff.d/font/devpost/charlib/LH
vs 
troff/troff.d/font/devpost/charlib/lh

**Comment by n-t-roff** [comment]
Thank you for reporting, this should be fixed now (can't test it on my file system). The fixing code is terrible, but more effort for just a single file name would not be adequate. Another solution would be to remove `\(LH`. It is a special AT&T logo, which is likely not used anymore. It does not exist for the standard option `-Tps` and is displaced in Solaris troff (and hence Heirloom). It works fine in DWB. I don't think it's worth to investigate why it is displaced. If someone is interested pull requests are welcome :)

**Comment by bapt** [comment]
I confirm it is ok.

Thank you
