### ISSUE TITLE
Refer output broken

### ISSUE THREAD

**Issue by bentley** [n-t-roff/heirloom-doctools#32]
heirloom-doctools-160217 has broken refer output.

Consider the following simple bibliography:

    %T OpenBSD.org
    %I The OpenBSD Foundation
    %B http://www.openbsd.org/

`$ printf '.[\nopenbsd\n.]\n' | /usr/local/heirloom-doctools/bin/refer -p bib`

On 150406, the output was as follows:

    .ds [F 1
    .]-
    .ds [T OpenBSD.org
    .ds [I The OpenBSD Foundation
    .ds [B http://www.openbsd.org/
    .nr [T 0
    .nr [A 0
    .nr [O 0
    .][ 3 article-in-book

On 160217, the output is as follows:

    .]-
    .nr [T 0
    .nr [A 0
    .nr [O 0
    .][ 0 other

**Comment by n-t-roff** [comment]
Thank you very much for this bug report! I had done a lot of regression tests but I had not expected refer issues since the changes had not been significant (I thought).

There are no substantial changes since 160217, so this actually a release version bugfix. Since we don't have a "incompatibility.feature.bugfix" version scheme I suggest to create a new release version 160308.
